DATASET:
  TRANSFORMS:
    CENTER_CROP: null
    RESIZE:
    - 100
    - 200
TRAINING:
  MODEL:
    NAME: CNN100_3Conv_3Pool_2FC
    REGISTRY: PIECE_CLASSIFIER
_BASE_: config://piece_classifier/_base.yaml
