DATASET:
  TRANSFORMS:
    CENTER_CROP: null
    RESIZE:
    - 100
    - 100
TRAINING:
  MODEL:
    NAME: CNN100_3Conv_3Pool_2FC
    REGISTRY: OCCUPANCY_CLASSIFIER
_BASE_: config://occupancy_classifier/_base.yaml
