DATASET:
  TRANSFORMS:
    CENTER_CROP:
    - 50
    - 50
    RESIZE:
    - 50
    - 50
TRAINING:
  MODEL:
    NAME: CNN50_2Conv_2Pool_2FC
    REGISTRY: OCCUPANCY_CLASSIFIER
_BASE_: config://occupancy_classifier/_base.yaml
