DATASET:
  TRANSFORMS:
    CENTER_CROP: null
    RESIZE:
    - 50
    - 50
TRAINING:
  MODEL:
    NAME: CNN50_2Conv_2Pool_3FC
    REGISTRY: OCCUPANCY_CLASSIFIER
_BASE_: config://occupancy_classifier/_base.yaml
